# DO NOT EDIT THIS FILE!
#
# Python module unscrambler__POA generated by omniidl

import omniORB
omniORB.updateModule("unscrambler__POA")

# ** 1. Stub files contributing to this module
import unscrambler_idl

# ** 2. Sub-modules

# ** 3. End
