package unscrambler;

/**
* unscrambler/unscrambleridlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from unscrambler.idl
* Tuesday, May 25, 2021 1:09:16 PM SGT
*/

public interface unscrambleridlOperations 
{
  boolean addToUsersArray (String username);
  boolean answerIsCorrect (String username, String answer);
  String ScrambledWord (String username);
  String reScramble (String username);
  short returnAttemptsLeft (String username);
  void exitUser (String username);
} // interface unscrambleridlOperations
