package unscrambler;

/**
* unscrambler/unscrambleridl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from unscrambler.idl
* Tuesday, May 25, 2021 1:09:16 PM SGT
*/

public interface unscrambleridl extends unscrambleridlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface unscrambleridl
